version: '3.1'
services:
  # comment out platform-changelog-api stanza to disable it
  # platform-changelog-api:
  #     image: platform-changelog-go
  #     ports:
  #         - "8000:8000"
  #     environment:
  #         DB_HOST: "localhost"
  #     command:
  #         - /pc-api
  #     depends_on:
  #         - platform-changelog-db
  payload-tracker-db:
      image: postgres
      restart: always
      environment:
          POSTGRES_PASSWORD: crc
          POSTGRES_USER: crc
          POSTGRES_DB: gumbaroo
      ports:
          - "5432:5432"